"""empty message

Revision ID: 5b3ba1fe33c9
Revises: 94168dbf7862
Create Date: 2025-10-01 19:45:33.622088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3ba1fe33c9'
down_revision = '94168dbf7862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked',
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('blocked_id'),
    sa.UniqueConstraint('blocked_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocked')
    # ### end Alembic commands ###
