"""empty message

Revision ID: 94168dbf7862
Revises: 244e219814f6
Create Date: 2025-10-01 17:47:08.767934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94168dbf7862'
down_revision = '244e219814f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celebrity',
    sa.Column('celebrity_id', sa.Integer(), nullable=False),
    sa.Column('celebrity_name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=500), nullable=False),
    sa.Column('Insta', sa.String(length=500), nullable=False),
    sa.Column('yt', sa.String(length=500), nullable=False),
    sa.Column('twitter', sa.String(length=500), nullable=False),
    sa.Column('profile', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('celebrity_id'),
    sa.UniqueConstraint('Insta'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('celebrity_id'),
    sa.UniqueConstraint('celebrity_name'),
    sa.UniqueConstraint('twitter'),
    sa.UniqueConstraint('yt')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celebrity')
    # ### end Alembic commands ###
